const FACEBOOK_MAX_CHARACTERS = 2200;
const INSTAGRAM_MAX_CHARACTERS = 280;
const WORDS_LABEL = "Words";
const CHARACTERS_LABEL = "Characters";
const INSTAGRAM_LABEL = "Instagram";
const FACEBOOK_LABEL = "Facebook";

export {
  CHARACTERS_LABEL,
  FACEBOOK_LABEL,
  FACEBOOK_MAX_CHARACTERS,
  INSTAGRAM_LABEL,
  INSTAGRAM_MAX_CHARACTERS,
  WORDS_LABEL,
};
